#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Putting the first blocks in place => New Apps in ~/the_pyramid"
  mkdir ~/the_pyramid && cd ~/the_pyramid
  curl http://cachefly.alfredapp.com/alfred_1.3.1_261.dmg -o "alfred_1.3.1_261.dmg"
  successfully hdiutil attach alfred_1.3.1_261.dmg
  curl https://github.com/downloads/b4winckler/macvim/MacVim-snapshot-65.tbz -o "MacVim_65.tbz"
  successfully tar xjf MacVim_65.tbz

echo "Fixing permissions ..."
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Putting Homebrew location earlier in PATH ..."
  successfully echo "# recommended by brew doctor export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing GNU Compiler Collection and dependencies ..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Scaling the great stones up to arrange Git"
  successfully brew install git

echo "Etch your name into the stones of Git"
  echo "Enter Your Full Name for Git"
  read name
  git config --global user.name "$name"
  echo "Enter your email address for Git"
  read email
  git config --global user.email "$email"

echo "Installing Oh-My-Zshell, which is just an awesome shell"
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Installing MySql"
  successfully brew install mysql
  unset TMPDIR
  mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp

echo "Installing Postgres, a good open source relational database ..."
  successfully brew link ossp-uuid
  successfully brew install postgres --no-python

echo "Installing ack, a good way to search through files ..."
  successfully brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  successfully brew install tmux

echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

echo "Installing RVM (Ruby Version Manager) and Ruby 1.9.3, which becomes the default ..."
  successfully curl -L https://get.rvm.io | bash -s stable --ruby
  successfully echo "
# RVM
  [[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler rails heroku pg foreman thin --no-rdoc --no-ri

echo "Installing Whim, Wistia Vim Plugins"
  mv ~/.vimrc ~/.vimrc.backup && mv ~/.gvimrc ~/.gvimrc.backup
  mkdir -p ~/.vim/autoload ~/.vim/bundle
  successfully curl https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim \
      > ~/.vim/autoload/pathogen.vim
  successfully git clone git://github.com/wistia/whim.git ~/.whim
  cd ~/.whim
  git submodule update --init
  ln -s ~/.whim/local/default.vimrc ~/.vimrc
  ln -s ~/.whim/local/default.gvimrc ~/.gvimrc
  cd ~/.whim/bundle/command-t/ruby/command-t
  rvm use system
  ruby extconf.rb
  make
  rvm use default

echo "Installing Redis, a fast, in-memory object store"
  successfully brew install redis

echo "Updating Rubygems"
  successfully gem update


